# Generated by Django 5.0.7 on 2024-07-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='OS',
            field=models.IntegerField(default=1, verbose_name='Ordem de serviço'),
        ),
    ]
