# Generated by Django 5.0.7 on 2024-07-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_patrimonio_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frota', models.IntegerField(max_length=6, verbose_name='Número de frota')),
                ('horimetro', models.IntegerField(verbose_name='Horimetro de máquina')),
                ('OS', models.IntegerField(default=0, verbose_name='Ordem de serviço')),
            ],
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='OS',
            field=models.IntegerField(default=0, verbose_name='Ordem de serviço'),
        ),
    ]
