# Generated by Django 5.0.7 on 2024-07-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_ultimapreventiva_alter_patrimonio_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimonio',
            name='OS',
        ),
        migrations.AddField(
            model_name='ultimapreventiva',
            name='HoradePreventiva',
            field=models.IntegerField(default=0, verbose_name='Preventiva de quantas horas'),
        ),
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='frota',
            field=models.IntegerField(default=0, verbose_name='Número de frota'),
        ),
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='horimetro',
            field=models.IntegerField(default=0, verbose_name='Horimetro de máquina'),
        ),
    ]
