# Generated by Django 5.0.7 on 2024-07-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0008_alter_ultimapreventiva_horadepreventiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimapreventiva',
            name='modelo',
            field=models.CharField(default='', max_length=100, verbose_name='Modelo de máquina'),
        ),
    ]
