# Generated by Django 5.0.7 on 2024-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0009_ultimapreventiva_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeçaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
