# Generated by Django 5.0.7 on 2024-07-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0010_peçautilizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='PeçaUtilizada',
        ),
        migrations.AddField(
            model_name='ultimapreventiva',
            name='pecas',
            field=models.ManyToManyField(to='maquinas.pecas'),
        ),
    ]
