# Generated by Django 5.0.7 on 2024-07-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0011_pecas_delete_peçautilizada_ultimapreventiva_pecas'),
        ('maquinas', '0012_pecas_predefinidas'),
    ]

    operations = [
    ]
