# Generated by Django 5.0.7 on 2024-07-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0013_merge_20240720_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='pecas',
            field=models.ManyToManyField(to='maquinas.pecas', verbose_name='Peças usadas'),
        ),
    ]
