# Generated by Django 5.0.7 on 2024-07-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0014_alter_ultimapreventiva_pecas'),
        ('maquinas', '0015_pecas_predefinidas copy'),
    ]

    operations = [
    ]
