# Generated by Django 5.0.7 on 2024-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0016_merge_20240721_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='frota',
            field=models.IntegerField(verbose_name='Número de frota'),
        ),
    ]
